# Generated by Django 5.0.4 on 2024-09-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('short_answer', 'Short Answer'), ('paragraph', 'Paragraph'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Check Boxes'), ('dropdown', 'Dropdowns'), ('file_upload', 'File Upload'), ('date', 'Date'), ('time', 'Time')], max_length=100)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='Multiple_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.question')),
            ],
        ),
    ]
